version: '3.7'

services:
  nginx:
    image: 'blacklabelops/nginx'
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    networks:
      - atlassiannet
    environment:
      - 'REVERSE_PROXY_BUFFERING='
      - 'REVERSE_PROXY_BUFFERS='
      - 'REVERSE_PROXY_BUFFERS_SIZE='

      - 'SERVER_NAME=jira.kamenev.name'
      - 'REVERSE_PROXY_LOCATION1=/jira'
      - 'REVERSE_PROXY_PASS1=http://jira:8080'


    ports:
      - '80:80'
      - '443:443'
    volumes:
      - nginxdata:/home/nginx
      - nginxwww:/var/lib/nginx/html
      #- /var/nginx/nginx.conf:/etc/nginx/nginx.conf
      #- /var/nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf

volumes:
  nginxdata:
    external: true
  nginxwww:
    external: true

networks:
  atlassiannet:
    external:
      name: network-atlassian
