version: '3.7'

services:
  db:
     image: mysql:latest
     container_name: mysql
     hostname: mysql
     volumes:
         - db_data:/var/lib/mysql
     restart: unless-stopped
     expose:
         - '3306'
     links:
         - jira
     environment:
         MYSQL_ROOT_PASSWORD: test
         MYSQL_DATABASE: jira
         MYSQL_USER: test
         MYSQL_PASSWORD: test
#   jira:
#     depends_on:
#       - db
#     image: wordpress:latest
#     :
#       - "8000:80"
#     restart: always
#     environment:
volumes:
  dbdata:
    external: true
networks:
  atlassiannet:
    external:
      name: network-atlassian
